### ISSUE TITLE
Make root cause analysis possible also for huge traces

### ISSUE THREAD

**Issue by mawHBT** [jenkinsci/peass-ci-plugin#131] opened 2022-04-27 05:50 UTC
### What feature do you want to see added?

If onlyOneCallRecording is set, no rca is possible because no calltree can be generated. You can exclude very often called methods but you have to know which ones. Therefore maybe a parameter onlyCallCountRecording would help to get information which methods are called how often.
If traces are too big and you have to set onlyOneCallRecording, maybe generating only a reduced calltree would help also.

**Comment by DaGeRe** [comment] 2023-02-16 11:08
Thanks for the issue, but this is a duplicate of https://github.com/jenkinsci/peass-ci-plugin/issues/81, so I'll close this.

**Closed by DaGeRe** 2023-02-16 11:08 UTC
Labels: enhancement
