### ISSUE TITLE
Mark build as unstable if exception is thrown in RCA

### ISSUE THREAD

**Issue by mawHBT** [jenkinsci/peass-ci-plugin#147] opened 2022-06-01 10:17 UTC
### What feature do you want to see added?

We had an exception in RCA, no calltree was generated. Build itself was green, so we would not have recognized it, if we didn't check explicitly. Builds should be marked as unstable if exception is thrown in RCA-Log.

[exception.txt](https://github.com/jenkinsci/peass-ci-plugin/files/8813212/exception.txt)

**Comment by DaGeRe** [comment] 2022-06-03 15:09
This should work beginning with https://github.com/jenkinsci/peass-ci-plugin/commit/2eb716270d66e16efa166eb628f94c5ef31b7fb0, can you confirm this?

**Comment by mawHBT** [comment] 2022-06-07 10:59
We have no test with failing RCA at the moment, so we can not check this now.

**Comment by DaGeRe** [comment] 2023-02-16 11:04
Since this was not reproducible for more than half a year, I'll close this issue.

**Closed by DaGeRe** 2023-02-16 11:04 UTC
Labels: enhancement
